apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-server
  labels:
    app: worker-server
spec:
  selector:
    matchLabels:
      app: worker-server
  template:
    metadata:
      labels:
        app: worker-server
    spec:
      containers:
        - name: q-handler-server
          image: gcr.io/assignments-252803/worker-server-image-1
          env:
            - name: MYSQL_DB_HOST
              value: 127.0.0.1:3306
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.16
          command: ["/cloud_sql_proxy",
                    "-instances=assignments-252803:us-west1:csci5253project=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
